# Setup
title:        XX.
tagline:      菜鸡的咆哮.
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Author name
  url:        http://XXaccepted.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
